# Generated by Django 3.0.6 on 2020-06-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200523_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='media/user_image'),
        ),
    ]
