# Generated by Django 3.0.6 on 2020-05-21 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='poll_choice',
        ),
    ]
