# Generated by Django 3.0.6 on 2020-06-06 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0002_remove_poll_poll_choice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ('-poll_created',)},
        ),
        migrations.AddField(
            model_name='poll',
            name='poll_has_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='choice',
            name='poll_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.Poll'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.Choice')),
                ('poll_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_vote', to='polls.Poll')),
                ('voted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('poll_name', 'voted_by')},
            },
        ),
    ]
