# Generated by Django 3.0.6 on 2020-06-21 13:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0005_auto_20200618_0457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ('-poll_question',)},
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='choice_name',
            new_name='choice_id',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='poll_name',
            new_name='poll_id',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('poll_id', 'voted_by')},
        ),
    ]
